### ISSUE TITLE
patched

### ISSUE THREAD

**Issue by Rylazius** [0x24a/WarpPlusKeyGenerator-NG#1]
![image](https://github.com/user-attachments/assets/61e38c73-bfe1-4be9-9e05-679349890a7e)
this also happened to my own warp+ 12pb key which converts to warp only

**Comment by 0x24a** [comment]
It looks like it's just Cloudflare blocking our Base Keys, I'll be replacing them soon. :)

**Comment by 0x24a** [comment]
It should work now

**Comment by Lustaly** [comment]
patched again

**Comment by 0x24a** [comment]
> patched again

fixed again
