### ISSUE TITLE
Generation problems detected

### ISSUE THREAD

**Issue by walterwick** [0x24a/WarpPlusKeyGenerator-NG#10]
License Key:    1zIV9t63-zyp402F6-75gcZ81N
WARN    Generation problems detected, please open an issue at https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues

Keys:
1zIV9t63-zyp402F6-75gcZ81N

![image](https://github.com/user-attachments/assets/99c18a4a-bb53-497a-adc8-bcbbb56b98a8)

**Comment by 0x24a** [comment]
https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/9
