### ISSUE TITLE
https://warpplus-05522e68.cloudflareaccess.com/warp

### ISSUE THREAD

**Issue by strange8969** [0x24a/WarpPlusKeyGenerator-NG#16]
https://warpplus-05522e68.cloudflareaccess.com/warp
The default connection protocol for this team is MASQUE.

Open an issue or send an e-mail to [miku399993@gmail.com](mailto:miku399993@gmail.com) to let us know when it's full.

_Originally posted by @0x24a in https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/11#issuecomment-2461303436_

this link is full. please provide us the new link.

**Comment by 0x24a** [comment]
https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/11#issuecomment-2467210288
