### ISSUE TITLE
https://warpplus-fa6b812c.cloudflareaccess.com/warp

### ISSUE THREAD

**Issue by mohsaj** [0x24a/WarpPlusKeyGenerator-NG#18]
https://warpplus-fa6b812c.cloudflareaccess.com/warp
The default connection protocol for this team is MASQUE.

Open an issue or send an e-mail to [miku399993@gmail.com](mailto:miku399993@gmail.com) to let us know when it's full.

_Originally posted by @0x24a in https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/11#issuecomment-2467210288_
            

Tnx.
The default protocol is not set to MASQUE.
Pls edit and set it to masque.

![Screenshot_20241111_082557_1111](https://user-images.githubusercontent.com/63780066/384786747-f6a57307-761e-4038-8b8e-3d0774ba626a.jpg)

**Comment by mohsaj** [comment]
![Screenshot_20241111_082557_1111](https://github.com/user-attachments/assets/1bc79dec-5710-4a81-8aaf-e8efd0d8b95f)

**Comment by 0x24a** [comment]
The tunnel protocol is MASQUE.
That protocol option in your screenshot is the DNS Protocol.
