### ISSUE TITLE
The zero trust is full

### ISSUE THREAD

**Issue by MidnightKittenCat** [0x24a/WarpPlusKeyGenerator-NG#20]
The zero trust has no available seats

**Comment by Denver3D** [comment]
Ok thank you 😊

**Comment by AzerilWarframe** [comment]
i hope the newest one is also MASQUE

**Comment by 0x24a** [comment]
https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/11#issuecomment-2481958983

**Comment by 0x24a** [comment]
> i hope the newest one is also MASQUE

The next one will be
