### ISSUE TITLE
Zero Trust team for full for this month

### ISSUE THREAD

**Issue by odflix** [0x24a/WarpPlusKeyGenerator-NG#24]
https://warpplus-97906a78.cloudflareaccess.com/warp

it's full, waiting for your next team. Thank you

**Comment by 0x24a** [comment]
Nope, it's not full

**Comment by 0x24a** [comment]
WAIT IT IS

**Comment by 0x24a** [comment]
https://warpplus-c96eaf2e.cloudflareaccess.com/warp
![](https://zerotrust-seats-counter.24a.workers.dev/badge?team-id=warpplus-c96eaf2e&total-seats=50)
