### ISSUE TITLE
Account type free.

### ISSUE THREAD

**Issue by alexandrew83** [0x24a/WarpPlusKeyGenerator-NG#3]
Account Type:   free
Data Limit:     1923837100 GiB
License Key:    vK70R9y5-w78Rua30-2s418mTN

How do  I get this to generate plus unlimited keys?

**Comment by 0x24a** [comment]
This isn't a bug, You can't generate Warp+ keys with unlimited traffic, but you can generate keys with very high limits.

**Comment by alexandrew83** [comment]
How do I change to generate those Warp+ keys?

**Comment by 0x24a** [comment]
This program generates Warp+ Key with 1.92EB of traffic by default, which is enough in most cases.

**Comment by 0x24a** [comment]
The principle of this program is that Warp+ users get 1GB of traffic for every person they invite, and this program generates a lot of fake invitations to get a large quota.
That's why it is shown as "Free key".
