### ISSUE TITLE
Account type bug??

### ISSUE THREAD

**Issue by QuMinh2410** [0x24a/WarpPlusKeyGenerator-NG#5]
Hi, first time using github, sorry if this question have already been answered somewhere.
In the preview image, it generate and account with "type: limited", but when i use the script it only generate an account with "type: Free" which mean if i use the key i only get warp but not warp+ on cloudflare app

**Comment by 0x24a** [comment]
No, you can still get WARP+ by using that key :D
The preview image is outdated, i will change it soon

**Comment by QuMinh2410** [comment]
Don't think thats WARP+
This is when i'm using my key, it's showing account type: Limited and the CloudFlare app showing Warp+ with data remaining
![image](https://github.com/user-attachments/assets/b3ef0917-5742-47e6-a63b-774c94e79e81)
![image](https://github.com/user-attachments/assets/07735d34-77b5-4fbb-a525-9fa5aa7102dc)


And this is when i'm using the key generate from the script. No WARP+ just WARP, And the 1.1.1.1 app not showing the data remaining as well
![image](https://github.com/user-attachments/assets/f7b6f0d6-cff2-45b0-8c16-46e96133c648)
![image](https://github.com/user-attachments/assets/c5039d04-233d-4994-9827-8d8bbce4c685)

**Comment by 0x24a** [comment]
This is strange. I've just tested it on the 1.1.1.1 mobile app, and it's working normally with WARP+ enabled. I'll mark this as a bug and try to find the cause.

**Comment by QuMinh2410** [comment]
It might be warp+ showing in app but if you go to 1.1.1.1./cdn-cgi/trace it will show you warp=on when it supposed to be warp=plus

**Comment by kda2495** [comment]
Confirm, CF changed something. Only free accounts.

**Comment by QuMinh2410** [comment]
Lastest news, Referral program will be concluded on Nov 1st. Maybe thats why we can only generate free account

**Comment by kda2495** [comment]
> Lastest news, Referral program will be concluded on Nov 1st. Maybe thats why we can only generate free account

Yeah, I think that's why.

**Comment by Mon-ius** [comment]
Cloudflare changed the logic between account management. I can confirm that on my previous testing API results.
But u can still generate such thing by using the old school way 🤗

**Comment by kda2495** [comment]
> Cloudflare changed the logic between account management. I can confirm that on my previous testing API results.
> But u can still generate such thing by using the old school way 🤗

What old-school way?😁 I can generate only free configs. Old-school way - just with referral program?)

**Comment by 0x24a** [comment]
Please see https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/9
