### ISSUE TITLE
Genration Problems Detected

### ISSUE THREAD

**Issue by galahal** [0x24a/WarpPlusKeyGenerator-NG#7]
**WARP+ Key Generator
By 0x24a, Version v0.0.4
Loading basekeys from the Github Repo...

Loaded 11 Base Keys

Generating... (1/1)
Account Type:   free
Data Limit:     0 GiB
License Key:    65sag70f-7lg3U58L-c38mEB07
WARN    Generation problems detected, please open an issue at https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues**

**Comment by kda2495** [comment]
I confirm. Generates only free account, CF changed something.

**Comment by haitemk** [comment]
Its most likely cause the base keys were overused, if you generated any accounts before this replace the base keys

**Comment by kda2495** [comment]
> Its most likely cause the base keys were overused, if you generated any accounts before this replace the base keys

Have you tried another basic keys? I've changed and nothing happen.

**Comment by 0x24a** [comment]
Please see https://github.com/0x24a/WarpPlusKeyGenerator-NG/issues/9
