### ISSUE TITLE
Cloudflare not accepting referral codes

### ISSUE THREAD

**Issue by kietdev-218** [0x24a/WarpPlusKeyGenerator-NG#8]
{"result":null,"success":false,"errors":[{"code":1070,"message":"We are no longer accepting referral codes. Please continue to sign up with a free account."}],"messages":[]}\n

**Comment by 0x24a** [comment]
https://support.cloudflarewarp.com/hc/en-us/articles/360025588054-How-do-referrals-work
> Note: Cloudflare will conclude the referral program for WARP+ on November 1, 2024. At that time, new referral codes will no longer be provided. When your device consumes existing referral allotment you will automatically migrate to the WARP free plan. You will not lose connectivity.

All key generators will stop working. :(
